apiVersion: v1
kind: Pod
metadata:
  name: two-containers

spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
    - name: ubuntu
      image: ubuntu
      volumeMounts:
        - name: shared-data
          mountPath: /shared-data
      command: ["/bin/bash"]
      args: ["-c", "echo Hello from the ubuntu container > /shared-data/index.html"]