apiVersion: v1
kind: Service
metadata:
  name: expose
  labels:
    app: loadbalancer

spec:
  selector:
    app.kubernetes.io/name: spring
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80